root - WARNING - downloading a 1959.387MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124433
root - WARNING - downloading a 2160.400MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124732
root - WARNING - downloading a 2094.838MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124075
root - WARNING - downloading a 2209.730MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124869
root - ERROR - During session 715093703 processing : Nan in lfp of Probe 810755801, probe skipped.
root - ERROR - Error in session: 715093703, probe id: 810755801
root - ERROR - Traceback (most recent call last):
  File "/home/acampbell/NeuropixelsLFPOnRamp/DetectingSWRs/ABI_Pipeline/allen_swr_detector.py", line 442, in process_session
    raise ValueError(f"During session {session_id} processing : Nan in lfp of Probe {probe_id}, probe skipped.")  # Raise error
ValueError: During session 715093703 processing : Nan in lfp of Probe 810755801, probe skipped.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acampbell/NeuropixelsLFPOnRamp/DetectingSWRs/ABI_Pipeline/allen_swr_detector.py", line 445, in process_session
    del lfp  # Delete lfp from memory to save RAM
UnboundLocalError: local variable 'lfp' referenced before assignment

root - WARNING - downloading a 2331.512MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124036
root - WARNING - downloading a 2215.868MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124436
root - WARNING - downloading a 2190.851MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124865
root - WARNING - downloading a 2169.374MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124246
root - WARNING - downloading a 2297.802MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124040
root - WARNING - downloading a 1940.339MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124073
root - WARNING - downloading a 2187.403MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124867
root - WARNING - downloading a 2170.997MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124442
root - WARNING - downloading a 68.456MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124042
root - WARNING - downloading a 68.940MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124044
root - WARNING - downloading a 2071.962MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124244
root - WARNING - downloading a 1215.548MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124046
root - WARNING - downloading a 1880.957MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124077
root - WARNING - downloading a 2230.074MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124871
root - WARNING - downloading a 2103.813MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124446
root - WARNING - downloading a 2402.390MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124248
root - WARNING - downloading a 2165.388MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124079
root - WARNING - downloading a 2174.110MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124328
root - WARNING - downloading a 2120.599MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124875
root - WARNING - downloading a 2191.126MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124448
root - WARNING - downloading a 2257.084MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124332
root - WARNING - downloading a 1943.530MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124082
root - ERROR - During session 721123822 processing : Nan in lfp of Probe 760213150, probe skipped.
root - ERROR - Error in session: 721123822, probe id: 760213150
root - ERROR - Traceback (most recent call last):
  File "/home/acampbell/NeuropixelsLFPOnRamp/DetectingSWRs/ABI_Pipeline/allen_swr_detector.py", line 442, in process_session
    raise ValueError(f"During session {session_id} processing : Nan in lfp of Probe {probe_id}, probe skipped.")  # Raise error
ValueError: During session 721123822 processing : Nan in lfp of Probe 760213150, probe skipped.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acampbell/NeuropixelsLFPOnRamp/DetectingSWRs/ABI_Pipeline/allen_swr_detector.py", line 445, in process_session
    del lfp  # Delete lfp from memory to save RAM
UnboundLocalError: local variable 'lfp' referenced before assignment

root - WARNING - downloading a 2139.261MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124252
root - ERROR - During session 756029989 processing : Nan in lfp of Probe 760640097, probe skipped.
root - ERROR - Error in session: 756029989, probe id: 760640097
root - ERROR - Traceback (most recent call last):
  File "/home/acampbell/NeuropixelsLFPOnRamp/DetectingSWRs/ABI_Pipeline/allen_swr_detector.py", line 442, in process_session
    raise ValueError(f"During session {session_id} processing : Nan in lfp of Probe {probe_id}, probe skipped.")  # Raise error
ValueError: During session 756029989 processing : Nan in lfp of Probe 760640097, probe skipped.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acampbell/NeuropixelsLFPOnRamp/DetectingSWRs/ABI_Pipeline/allen_swr_detector.py", line 445, in process_session
    del lfp  # Delete lfp from memory to save RAM
UnboundLocalError: local variable 'lfp' referenced before assignment

root - WARNING - downloading a 2073.367MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123541
root - WARNING - downloading a 1491.276MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124272
root - WARNING - downloading a 2334.230MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124330
root - WARNING - downloading a 2174.458MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123691
root - WARNING - downloading a 1768.140MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123539
root - WARNING - downloading a 2353.993MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124250
root - WARNING - downloading a 2024.186MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123383
root - WARNING - downloading a 2060.334MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123543
root - WARNING - downloading a 2256.483MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124334
root - WARNING - downloading a 2225.204MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123689
root - WARNING - downloading a 2371.660MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124254
root - WARNING - downloading a 1824.374MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123550
root - WARNING - downloading a 2211.459MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124337
root - WARNING - downloading a 2242.189MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123381
root - WARNING - downloading a 1952.072MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123687
root - WARNING - downloading a 2424.395MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124797
root - WARNING - downloading a 1716.037MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123546
root - ERROR - During session 757216464 processing : Nan in lfp of Probe 769322747, probe skipped.
root - ERROR - Error in session: 757216464, probe id: 769322747
root - ERROR - Traceback (most recent call last):
  File "/home/acampbell/NeuropixelsLFPOnRamp/DetectingSWRs/ABI_Pipeline/allen_swr_detector.py", line 442, in process_session
    raise ValueError(f"During session {session_id} processing : Nan in lfp of Probe {probe_id}, probe skipped.")  # Raise error
ValueError: During session 757216464 processing : Nan in lfp of Probe 769322747, probe skipped.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acampbell/NeuropixelsLFPOnRamp/DetectingSWRs/ABI_Pipeline/allen_swr_detector.py", line 445, in process_session
    del lfp  # Delete lfp from memory to save RAM
UnboundLocalError: local variable 'lfp' referenced before assignment

root - WARNING - downloading a 1911.574MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124573
root - WARNING - downloading a 1951.453MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123385
root - WARNING - downloading a 2102.408MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123693
root - WARNING - downloading a 2196.770MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124686
root - WARNING - downloading a 2018.774MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124571
root - WARNING - downloading a 857.143MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123548
root - WARNING - downloading a 2334.079MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124799
root - WARNING - downloading a 2056.494MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123695
root - WARNING - downloading a 2112.436MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123657
root - WARNING - downloading a 2230.525MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124507
root - WARNING - downloading a 2047.209MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124575
root - WARNING - downloading a 2276.807MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124690
root - WARNING - downloading a 2059.562MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124795
root - WARNING - downloading a 1736.853MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124577
root - WARNING - downloading a 1840.103MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123879
root - WARNING - downloading a 2291.848MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124504
root - WARNING - downloading a 2064.311MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123653
root - WARNING - downloading a 2169.411MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124697
root - WARNING - downloading a 2215.269MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124582
root - WARNING - downloading a 1947.330MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124801
root - WARNING - downloading a 2175.676MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123881
root - WARNING - downloading a 2260.150MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124651
root - WARNING - downloading a 2148.685MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124502
root - WARNING - downloading a 2220.086MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124695
root - WARNING - downloading a 1948.417MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123655
root - WARNING - downloading a 2358.050MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123885
root - WARNING - downloading a 2187.153MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124803
root - WARNING - downloading a 2084.094MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124748
root - WARNING - downloading a 2048.768MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124509
root - WARNING - downloading a 1941.532MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124647
root - WARNING - downloading a 2290.140MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123661
root - WARNING - downloading a 2499.722MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124806
root - WARNING - downloading a 2426.822MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124750
root - WARNING - downloading a 2338.293MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124511
root - WARNING - downloading a 2078.225MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026123659
root - WARNING - downloading a 2369.496MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124649
root - WARNING - downloading a 1631.287MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124752
root - ERROR - Error in session: 773418906, probe id: 792676154
root - ERROR - Traceback (most recent call last):
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/api/warehouse_cache/caching_utilities.py", line 104, in call_caching
    return read()
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_cache.py", line 774, in read_nwb
    reader = pynwb.NWBHDF5IO(str(path), 'r')
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/hdmf/utils.py", line 645, in func_call
    return func(args[0], **pargs)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/pynwb/__init__.py", line 234, in __init__
    super().__init__(path, manager=manager, mode=mode, file=file_obj, comm=comm, driver=driver)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/hdmf/utils.py", line 645, in func_call
    return func(args[0], **pargs)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/hdmf/backends/hdf5/h5tools.py", line 71, in __init__
    raise UnsupportedOperation(msg)
hdmf.backends.errors.UnsupportedOperation: Unable to open file /space/scratch/allen_visbehave_data/session_773418906/probe_792676154_lfp.nwb in 'r' mode. File does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/api/warehouse_cache/caching_utilities.py", line 96, in call_caching
    data = fetch()
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/ecephys_project_warehouse_api.py", line 93, in get_probe_lfp_data
    well_known_files = build_and_execute(
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/utilities.py", line 73, in build_and_execute
    return execute_templated(env, "__tmp__", engine=engine, **kwargs)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/utilities.py", line 93, in execute_templated
    return engine(rendered)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/rma_engine.py", line 96, in get_rma_tabular
    response = pd.DataFrame(self.get_rma_list(query))
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/rma_engine.py", line 91, in get_rma_list
    for chunk in self.get_rma(query):
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/rma_engine.py", line 77, in get_rma
    response_json = requests.get(current_url).json()
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acampbell/NeuropixelsLFPOnRamp/DetectingSWRs/ABI_Pipeline/allen_swr_detector.py", line 424, in process_session
    lfp = session.get_lfp(probe_id)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_session.py", line 399, in get_lfp
    lfp = self.api.get_lfp(probe_id)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_session_api/ecephys_nwb_session_api.py", line 167, in get_lfp
    lfp_file = self._probe_nwbfile(probe_id)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_session_api/ecephys_nwb_session_api.py", line 118, in _probe_nwbfile
    return self.probe_lfp_paths[probe_id]()
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/api/warehouse_cache/caching_utilities.py", line 179, in one_file_call_caching
    return call_caching(
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/api/warehouse_cache/caching_utilities.py", line 129, in call_caching
    return call_caching(
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/api/warehouse_cache/caching_utilities.py", line 129, in call_caching
    return call_caching(
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/api/warehouse_cache/caching_utilities.py", line 96, in call_caching
    data = fetch()
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/ecephys_project_warehouse_api.py", line 93, in get_probe_lfp_data
    well_known_files = build_and_execute(
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/utilities.py", line 73, in build_and_execute
    return execute_templated(env, "__tmp__", engine=engine, **kwargs)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/utilities.py", line 93, in execute_templated
    return engine(rendered)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/rma_engine.py", line 96, in get_rma_tabular
    response = pd.DataFrame(self.get_rma_list(query))
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/rma_engine.py", line 91, in get_rma_list
    for chunk in self.get_rma(query):
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/rma_engine.py", line 77, in get_rma
    response_json = requests.get(current_url).json()
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

root - WARNING - downloading a 2514.017MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124655
root - WARNING - downloading a 2184.626MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124754
root - WARNING - downloading a 2077.816MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124653
root - WARNING - downloading a 2154.087MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026124756
root - WARNING - downloading a 2552.846MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026125023
root - WARNING - downloading a 2311.501MiB file from http://api.brain-map.org//api/v2/well_known_file_download/1026125027
root - ERROR - Error in session: 799864342, probe id: 805579706
root - ERROR - Traceback (most recent call last):
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/api/warehouse_cache/caching_utilities.py", line 104, in call_caching
    return read()
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_cache.py", line 774, in read_nwb
    reader = pynwb.NWBHDF5IO(str(path), 'r')
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/hdmf/utils.py", line 645, in func_call
    return func(args[0], **pargs)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/pynwb/__init__.py", line 234, in __init__
    super().__init__(path, manager=manager, mode=mode, file=file_obj, comm=comm, driver=driver)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/hdmf/utils.py", line 645, in func_call
    return func(args[0], **pargs)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/hdmf/backends/hdf5/h5tools.py", line 71, in __init__
    raise UnsupportedOperation(msg)
hdmf.backends.errors.UnsupportedOperation: Unable to open file /space/scratch/allen_visbehave_data/session_799864342/probe_805579706_lfp.nwb in 'r' mode. File does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/api/warehouse_cache/caching_utilities.py", line 96, in call_caching
    data = fetch()
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/ecephys_project_warehouse_api.py", line 93, in get_probe_lfp_data
    well_known_files = build_and_execute(
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/utilities.py", line 73, in build_and_execute
    return execute_templated(env, "__tmp__", engine=engine, **kwargs)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/utilities.py", line 93, in execute_templated
    return engine(rendered)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/rma_engine.py", line 96, in get_rma_tabular
    response = pd.DataFrame(self.get_rma_list(query))
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/rma_engine.py", line 91, in get_rma_list
    for chunk in self.get_rma(query):
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/rma_engine.py", line 77, in get_rma
    response_json = requests.get(current_url).json()
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acampbell/NeuropixelsLFPOnRamp/DetectingSWRs/ABI_Pipeline/allen_swr_detector.py", line 424, in process_session
    lfp = session.get_lfp(probe_id)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_session.py", line 399, in get_lfp
    lfp = self.api.get_lfp(probe_id)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_session_api/ecephys_nwb_session_api.py", line 167, in get_lfp
    lfp_file = self._probe_nwbfile(probe_id)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_session_api/ecephys_nwb_session_api.py", line 118, in _probe_nwbfile
    return self.probe_lfp_paths[probe_id]()
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/api/warehouse_cache/caching_utilities.py", line 179, in one_file_call_caching
    return call_caching(
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/api/warehouse_cache/caching_utilities.py", line 129, in call_caching
    return call_caching(
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/api/warehouse_cache/caching_utilities.py", line 129, in call_caching
    return call_caching(
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/api/warehouse_cache/caching_utilities.py", line 96, in call_caching
    data = fetch()
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/ecephys_project_warehouse_api.py", line 93, in get_probe_lfp_data
    well_known_files = build_and_execute(
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/utilities.py", line 73, in build_and_execute
    return execute_templated(env, "__tmp__", engine=engine, **kwargs)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/utilities.py", line 93, in execute_templated
    return engine(rendered)
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/rma_engine.py", line 96, in get_rma_tabular
    response = pd.DataFrame(self.get_rma_list(query))
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/rma_engine.py", line 91, in get_rma_list
    for chunk in self.get_rma(query):
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/allensdk/brain_observatory/ecephys/ecephys_project_api/rma_engine.py", line 77, in get_rma
    response_json = requests.get(current_url).json()
  File "/home/acampbell/miniconda3/envs/allensdk_env/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

root - ERROR - During session 797828357 processing : Nan in lfp of Probe 805579749, probe skipped.
root - ERROR - Error in session: 797828357, probe id: 805579749
root - ERROR - Traceback (most recent call last):
  File "/home/acampbell/NeuropixelsLFPOnRamp/DetectingSWRs/ABI_Pipeline/allen_swr_detector.py", line 442, in process_session
    raise ValueError(f"During session {session_id} processing : Nan in lfp of Probe {probe_id}, probe skipped.")  # Raise error
ValueError: During session 797828357 processing : Nan in lfp of Probe 805579749, probe skipped.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acampbell/NeuropixelsLFPOnRamp/DetectingSWRs/ABI_Pipeline/allen_swr_detector.py", line 445, in process_session
    del lfp  # Delete lfp from memory to save RAM
UnboundLocalError: local variable 'lfp' referenced before assignment

